name: myenv
channels:
  - conda-forge
dependencies:
  - python=3.6
  - matplotlib=3.2.2
  - pandas=1.1.5
 # - opencv=4.1.2
  - scipy
  - Cython         
  - Pillow
  - PyYAML
  #- tensorboard=1.6
  - tqdm
  - seaborn
  #- thop  
  - pycocotools=2.0 
  - gdown
  - future
  - scikit-build
  - setuptools=58.3.0
  #- testresources

